### ISSUE TITLE
two problems

### ISSUE THREAD

**Issue by darbe** [chaolongzhang/sinaWeibo#2]
in send weibo_sender.py，
‘’‘ # self.http.headers["Content-Type"] = "application/octet-stream"
        image_name = image_url
        try:
            f = self.http.get( image_name, timeout=30 )‘’’
 f = self.http.get( image_name, timeout=30 ) -->  f = self.session.get( image_name, timeout=30 ) I think
 and in spider_factory.py
I think we should add lock

**Comment by zchlong** [comment]
Yeah, you're right. f = self.http.get( image_name, timeout=30 ) --> f = self.session.get( image_name, timeout=30 ).
But lock, i think, is not necessary because the sending speed is very slow.
