### ISSUE TITLE
Linux提示403是怎么回事呢？

### ISSUE THREAD

**Issue by sid2656** [chaolongzhang/sinaWeibo#5]
同样的代码在Windows下可以执行；但是放到Linux下，就提示403；登录那块

**Comment by 279632990** [comment]
mac下也可以,但是linux就是报错了

**Comment by liangzhen6** [comment]
各位老铁解决了吗？
我在mac下也可以，在linux也报错，我发现是登录这一段
weibo_login.py---->71行。
resp = session.post(
        'http://login.sina.com.cn/sso/login.php?client=%s' % WBCLIENT,
        data=data
    )
    print(resp.text)

这里打印resp.text在mac下与linux下不一样

mac下======================================
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=GBK" />
<title>ÐÂÀËÍ¨ÐÐÖ¤</title>


<script charset="utf-8" src="https://i.sso.sina.com.cn/js/ssologin.js"></script>
</head>
<body>
ÕýÔÚµÇÂ¼ ...
<script>
try{sinaSSOController.setCrossDomainUrlList({"retcode":0,"arrURL":["https:\/\/passport.97973.com\/sso\/crossdomain?action=login&savestate=1530766096","https:\/\/passport.weibo.cn\/sso\/crossdomain?action=login&savestate=1"]});}
		catch(e){
			var msg = e.message;
			var img = new Image();
			var type = 1;
			img.src = 'https://login.sina.com.cn/sso/debuglog?msg=' + msg +'&type=' + type;
		}try{sinaSSOController.crossDomainAction('login',function(){location.replace('http://weibo.com/ajaxlogin.php?framelogin=1&callback=parent.sinaSSOController.feedBackUrlCallBack&ssosavestate=1530766096&ticket=ST-NjIyNTMyMzkxNw==-1499230096-gz-63A74E63DB943E599496A7CEACE7298F-1&retcode=0');});}
		catch(e){
			var msg = e.message;
			var img = new Image();
			var type = 2;
			img.src = 'https://login.sina.com.cn/sso/debuglog?msg=' + msg +'&type=' + type;
		}
</script>
</body>
</html>

linux下=========================================
  <html>
                <head>
                <title>ÐÂÀËÍ¨ÐÐÖ¤</title>
                <meta http-equiv="refresh" content="0; url=&#39;http://weibo.com/ajaxlogin.php?framelogin=1&callback=parent.sinaSSOCon
troller.feedBackUrlCallBack&retcode=4049&reason=%CE%AA%C1%CB%C4%FA%B5%C4%D5%CA%BA%C5%B0%B2%C8%AB%A3%AC%C7%EB%CA%E4%C8%EB%D1%E9%D6%A4%C
2%EB&#39;"/>
                <meta http-equiv="Content-Type" content="text/html; charset=GBK" />
                </head>
                <body bgcolor="#ffffff" text="#000000" link="#0000cc" vlink="#551a8b" alink="#ff0000">
                <script type="text/javascript" language="javascript">
                location.replace("http://weibo.com/ajaxlogin.php?framelogin=1&callback=parent.sinaSSOController.feedBackUrlCallBack&re
tcode=4049&reason=%CE%AA%C1%CB%C4%FA%B5%C4%D5%CA%BA%C5%B0%B2%C8%AB%A3%AC%C7%EB%CA%E4%C8%EB%D1%E9%D6%A4%C2%EB");
                </script>
                </body>
                </html>

两种环境下<script>标签下数据不一样。

**Comment by chaolongzhang** [comment]
@liangzhen6 Linux登录失败可能是需要输入验证码的问题，返回的“reason=%CE%AA%C1%CB%C4%FA%B5%C4%D5%CA%BA%C5%B0%B2%C8%AB%A3%AC%C7%EB%CA%E4%C8%EB%D1%E9%D6%A4%C2%EB”是“reason=为了您的帐号安全，请输入验证码”。

**Comment by chaolongzhang** [comment]
@sid2656 @279632990  CentOS 6、Python 3环境测试可以登录。登录不成功应该是验证码的问题。

**Comment by 279632990** [comment]
@chaolongzhang 您好,我马上安装了centos6.8 32位的,用了python3.4    返回错误是
Traceback (most recent call last):
  File "/root/sinaWeibo-master/main.py", line 8, in <module>
    (http, uid) = wblogin()
  File "/root/sinaWeibo-master/weibo/weibo_login.py", line 72, in wblogin
    login_url = re.search('replace\\(\'([^\']+)\'\\)', resp.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by qiaohaoforever** [comment]
@chaolongzhang 请问如何取消登陆验证码呢？
